/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapagosineso;
import java.util.logging.Logger;
import java.awt.Cursor;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;

/*import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;*/
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import javax.swing.JFrame;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author camif
 */
public class ConsultaPagos1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaPagos
     */
    String idUser;
    
    
    
    public ConsultaPagos1(String idUsuario) {
        initComponents();
        idUser = idUsuario;
        
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PantallaRegistro_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfPaciente2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPagos2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateFilter1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfFolioSeleccionado = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 25)); // NOI18N
        jLabel2.setText("Consulta de Pagos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 230, 40));

        tfPaciente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPaciente2ActionPerformed(evt);
            }
        });
        tfPaciente2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPaciente2KeyReleased(evt);
            }
        });
        jPanel1.add(tfPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 300, -1));

        tbPagos2.setFont(new java.awt.Font("Dubai Light", 1, 20)); // NOI18N
        tbPagos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Nombre del Alumno ", "Nombre del Paciente", "Último Mes Pagado", "Concepto"
            }
        ));
        tbPagos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPagos2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPagos2);
        if (tbPagos2.getColumnModel().getColumnCount() > 0) {
            tbPagos2.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 890, 300));

        jButton2.setBackground(new java.awt.Color(218, 236, 243));
        jButton2.setFont(new java.awt.Font("Dubai Light", 1, 19)); // NOI18N
        jButton2.setText("Generar Recibo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 200, 40));

        jPanel2.setBackground(new java.awt.Color(201, 70, 70));

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administración y Finanzas");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1380, 40));

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 20)); // NOI18N
        jLabel3.setText("Nombre del Paciente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 210, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 600, 190, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 990, 60));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES2/logo-Inpro.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, -1, 60));

        jButton1.setBackground(new java.awt.Color(218, 236, 243));
        jButton1.setFont(new java.awt.Font("Dubai Light", 1, 19)); // NOI18N
        jButton1.setText("Generar Reporte ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, -1, 40));
        jPanel1.add(jDateFilter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 20)); // NOI18N
        jLabel6.setText("Folio seleccionado:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 220, -1, -1));

        tfFolioSeleccionado.setEditable(false);
        tfFolioSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFolioSeleccionadoActionPerformed(evt);
            }
        });
        jPanel1.add(tfFolioSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 90, -1));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, -1, -1));

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
            
  private void limpiartabla(DefaultTableModel modeloxx){
for (int i = 0; i < tbPagos2.getRowCount(); i++) {
modeloxx.removeRow(i);
i-=1;
}

}
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            MostrarRecibo();
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(ConsultaPagos1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfPaciente2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPaciente2KeyReleased
        // TODO add your handling code here:
        
        String fecha= "";
        
        if (jDateFilter1.getCalendar() != null){
            int year = jDateFilter1.getCalendar().get(Calendar.YEAR);
            int mes = jDateFilter1.getCalendar().get(Calendar.MONTH) + 1;
            int dia = jDateFilter1.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            String Smes = ((mes < 10) ? "0"+Integer.toString(mes) : Integer.toString(mes)); 

            fecha=""+year+"-"+Smes+"-"+dia;
        }
        
        
         
        String x=tfPaciente2.getText().toString();
        System.out.println(x);
        

        
        
      
        try {
            // TODO add your handling code here:
            DefaultTableModel modelo = (DefaultTableModel)tbPagos2.getModel();
            
            limpiartabla(modelo);
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");
            Statement stmt = con.createStatement();
          // ResultSet rs = stmt.executeQuery("SELECT * FROM registro WHERE Alumno LIKE '"+tfAlumno1.getText().toString()+"%'");
           ResultSet rs = stmt.executeQuery("SELECT * FROM inpro WHERE Paciente LIKE '%"+tfPaciente2.getText().toString()+"%' AND Fecha LIKE '%"+ fecha +"%'");
           
           
           
            
if(rs.next()) { //se valida si hay resultados
  do {
    	//String[] fila = {rs.getString(1),rs.getString(2),rs.getString(5),rs.getString(6)};
        String[] fila = {String.format("%05d",Integer.parseInt(rs.getString("Folio"))), 
                        rs.getString("Alumno"), 
                        rs.getString("Paciente"), 
                        rs.getString("Fecha"), 
                        rs.getString("Concepto")};
    	modelo.addRow(fila);
  } while(rs.next()); //repita mientras existan más datos
}
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaPagos1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_tfPaciente2KeyReleased

    private void tfPaciente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPaciente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPaciente2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            MostrarReporte(); 
            
            
                    } catch (JRException ex) {
            Logger.getLogger(ConsultaPagos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfFolioSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFolioSeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFolioSeleccionadoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tbPagos2.getSelectedRow() > -1){
            JFrame frame = new JFrame();
            PantallaModificacion_1 modif = new PantallaModificacion_1(tfFolioSeleccionado.getText(), idUser);
            frame.add(modif);
            frame.setSize(1000, 800);
            frame.setResizable(true);
            modif.setVisible(true);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            //modif.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un registro en la lista para continuar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbPagos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPagos2MouseClicked
        // TODO add your handling code here:
        tfFolioSeleccionado.setText((String) tbPagos2.getValueAt(tbPagos2.getSelectedRow(),0));
    }//GEN-LAST:event_tbPagos2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(tbPagos2.getSelectedRow() > -1){
            int option = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro seleccionado?\nEsta acción no se puede deshacer.", 
                                                       "Confirmar eliminación", 
                                                       YES_NO_OPTION);
            if(option == 0){
                try {
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");
                    Statement stmt = con.createStatement();
                    stmt.executeUpdate("DELETE FROM `inpro` WHERE `Folio` = " + Integer.parseInt(tfFolioSeleccionado.getText()));
                    DefaultTableModel modelo = (DefaultTableModel)tbPagos2.getModel();
                    modelo.removeRow(tbPagos2.getSelectedRow());
                    JOptionPane.showMessageDialog(null,"Registro con folio "+ tfFolioSeleccionado.getText() +" eliminado");
                } catch (HeadlessException | NumberFormatException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                    Logger.getLogger(ConsultaPagos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            tfFolioSeleccionado.setText("");
        }else{
            JOptionPane.showMessageDialog(null,"Seleccione un registro en la lista para continuar.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    
    //Clase renombrada "MostrarReporte();
    public void MostrarRecibo() throws Exception
        {
                 Class.forName("com.mysql.cj.jdbc.Driver");
       Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");
       

                // InputStream jasperStream = Thread.currentThread().getContextClassLoader().getResourceAsStream("report1.jasper");

                 //JasperReport reporte = (JasperReport) JRLoader.loadObject(jasperStream);
                 //JasperReport reporte = (JasperReport) JRLoader.loadObject(new File("report1.jasper"));
              // JasperReport reporte = (JasperReport) JRLoader.loadObject("report1.jasper");
              JasperReport reporte = JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/sistemapagosineso/report2_1.jrxml");
             
              Map parametrosx=new HashMap();
              //parametrosx.put("nombreingresado2", tfPaciente2.getText().toString
              String folioSelected = (String) tbPagos2.getValueAt(tbPagos2.getSelectedRow(), 0);
              parametrosx.put("folio", folioSelected.replaceFirst("^0+(?!$)", ""));
              
              JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametrosx, con);

              JasperViewer jviewer= new JasperViewer(jasperPrint,false);
                       jviewer.setTitle("Reporte de Ventas");
                       jviewer.setVisible(true);


               /*JRExporter exporter = new JRPdfExporter();

               exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
               exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportePDF.pdf"));
               exporter.exportReport();
               System.out.println("PDF GENERADO, NOMBRE: reportePDF.pdf");*/
               
        }
    
    //Clase para el botón "Mostrar Reporte"
    private void MostrarReporte() throws SQLException, JRException {
        String fecha= "";
        
        if (jDateFilter1.getCalendar() != null){
            int year = jDateFilter1.getCalendar().get(Calendar.YEAR);
            int mes = jDateFilter1.getCalendar().get(Calendar.MONTH) + 1;
            int dia = jDateFilter1.getCalendar().get(Calendar.DAY_OF_MONTH);

            String Smes = ((mes < 10) ? "0"+Integer.toString(mes) : Integer.toString(mes)); 

            fecha=""+year+"-"+Smes+"-"+dia;
        }
        
        File f= new File ("");

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");

        Map params = new HashMap();
        params.put("fecha", fecha);
        
       // JasperReport jr = JasperCompileManager.compileReport("src/sistemapagosineso/reportAcumuladoInpro.jrxml");
        JasperReport jr = JasperCompileManager.compileReport(f.getAbsolutePath()+"\\src\\sistemapagosineso/reportAcumuladoInpro.jrxml");

        JasperPrint jp = JasperFillManager.fillReport(jr,params,con);
        JasperViewer jv = new JasperViewer(jp,false);
        jv.setVisible(true);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateFilter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPagos2;
    private javax.swing.JTextField tfFolioSeleccionado;
    private javax.swing.JTextField tfPaciente2;
    // End of variables declaration//GEN-END:variables

    
}
