/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemapagosineso;

import java.sql.*;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author camif
 */
public class PantallaRegistro extends javax.swing.JInternalFrame {
    int ax=1;
    double bx=1.0;
    String cx="adasdasdasdasdas";
    String idUser;
    
    Connection con;
    
    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro(String idUsuario) {
        initComponents();
        idUser = idUsuario;
        
        encontrarUsuario();
        Vaciar();  
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoIneso = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jcbTratamiento = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbnVaciar = new javax.swing.JButton();
        rbclinica3 = new javax.swing.JRadioButton();
        rbclinica2 = new javax.swing.JRadioButton();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        tfAlumno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbCiclo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbGrupo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taObservaciones = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 278, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1438, 214, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbTratamiento.setBackground(new java.awt.Color(81, 154, 183));
        jcbTratamiento.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jcbTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ortodoncia", "Ortopedia" }));
        jPanel1.add(jcbTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 170, -1));

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel10.setText("Tratamiento:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel3.setText("Nombre Completo del Alumno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 290, -1));

        jButton1.setBackground(new java.awt.Color(218, 236, 243));
        jButton1.setFont(new java.awt.Font("Dubai Medium", 0, 19)); // NOI18N
        jButton1.setText("Registrar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 120, -1));

        jbnVaciar.setBackground(new java.awt.Color(218, 236, 243));
        jbnVaciar.setFont(new java.awt.Font("Dubai Medium", 0, 19)); // NOI18N
        jbnVaciar.setText("Vaciar");
        jbnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnVaciarActionPerformed(evt);
            }
        });
        jPanel1.add(jbnVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 120, -1));

        GrupoIneso.add(rbclinica3);
        rbclinica3.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        rbclinica3.setText("Clínica $300");
        rbclinica3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbclinica3ActionPerformed(evt);
            }
        });
        jPanel1.add(rbclinica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        GrupoIneso.add(rbclinica2);
        rbclinica2.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        rbclinica2.setText("Clínica $200");
        rbclinica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbclinica2ActionPerformed(evt);
            }
        });
        jPanel1.add(rbclinica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 150, -1));
        jPanel1.add(jDateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 290, 30));
        jPanel1.add(tfAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 290, -1));

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel6.setText("Nombre Completo del Paciente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        tfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(tfPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 290, -1));

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel11.setText("Fecha:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel7.setText("Grupo / Semestre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jcbCiclo.setBackground(new java.awt.Color(81, 154, 183));
        jcbCiclo.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jcbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Septiembre - Febrero 2022", "Marzo - Agosto 2023", " " }));
        jcbCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCicloActionPerformed(evt);
            }
        });
        jPanel1.add(jcbCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 320, -1));

        jPanel2.setBackground(new java.awt.Color(81, 154, 183));

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administración y Finanzas");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1410, 40));

        jLabel2.setFont(new java.awt.Font("Dubai Light", 1, 25)); // NOI18N
        jLabel2.setText("Registro de Pagos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 230, 40));

        jcbGrupo.setBackground(new java.awt.Color(81, 154, 183));
        jcbGrupo.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jcbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes - Grupo 2 / 5° Semestre", "Miércoles - Grupo 3 / 3° Semestre", "Viernes - Grupo 1 / 6° Semestre ", " " }));
        jPanel1.add(jcbGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 320, -1));

        jLabel9.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel9.setText("Ciclo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO-INESOO.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 370, 140));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 600, 370, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 290, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/MUELA.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 990, 60));

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 17)); // NOI18N
        jLabel8.setText("Observaciones:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, 20));

        taObservaciones.setColumns(20);
        taObservaciones.setRows(5);
        jScrollPane2.setViewportView(taObservaciones);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 320, -1));

        jLabel16.setText("Usuario activo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        tfUsuario.setEditable(false);
        jPanel1.add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1570, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPacienteActionPerformed

    private void rbclinica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbclinica2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbclinica2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        int year = jDateFecha.getCalendar().get(Calendar.YEAR);
        int mes = jDateFecha.getCalendar().get(Calendar.MONTH)+1;
        int dia = jDateFecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        String fecha=""+year+"-"+mes+"-"+dia;
        
        String concepto ="";

        if (rbclinica2.isSelected()) {
            concepto = "Clínica $200";
        }
        if (rbclinica3.isSelected()) {
            concepto = "Clínica $300";
        }
       
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");
            Statement stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO `ineso` (`Alumno`, `Paciente`, `Grupo`, `Ciclo`, `Fecha`, `Concepto`, `Tratamiento`, `Observaciones`, `usuario_creacion`, `usuario_modificacion`) "
                    + " VALUES('"+tfAlumno.getText()+"','"+
                    tfPaciente.getText()+"','"+
                    jcbGrupo.getSelectedItem()+"','"+
                    jcbCiclo.getSelectedItem()+"','"+
                    fecha+"','"+
                    concepto+"','"+
                    jcbTratamiento.getSelectedItem()+"','"+
                    taObservaciones.getText()+"','"+
                    idUser+"','"+
                    idUser+"')");
            JOptionPane.showMessageDialog(null,"El pago se ha registrado exitosamente");
        } catch (SQLException ex) {
            Logger.getLogger(PantallaRegistro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCicloActionPerformed

    private void jbnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnVaciarActionPerformed
        // TODO add your handling code here:
        GrupoIneso.clearSelection();
        Vaciar();
    }//GEN-LAST:event_jbnVaciarActionPerformed

    private void rbclinica3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbclinica3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbclinica3ActionPerformed


    private void encontrarUsuario(){
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/sistemapagos","root","");
            Statement stm = con.createStatement();
            String query = "SELECT nombre FROM usuarios WHERE id_usuario = '"+ idUser +"'";
            //System.out.println(query);
            ResultSet rs = stm.executeQuery(query);
            if(rs.next()){
                tfUsuario.setText(rs.getString("nombre"));
            }else{
                tfUsuario.setText("...");
            }
        } catch (Exception e) {
            Logger.getLogger(ConsultaPagos.class.getName()).log(Level.SEVERE, null, e);
            System.out.println("Error: "+e);
        }
    }
    
    private void Vaciar() {
        tfAlumno.setText("");
        tfPaciente.setText("");
        jDateFecha.setCalendar(null);  
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoIneso;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbnVaciar;
    private javax.swing.JComboBox<String> jcbCiclo;
    private javax.swing.JComboBox<String> jcbGrupo;
    private javax.swing.JComboBox<String> jcbTratamiento;
    private javax.swing.JRadioButton rbclinica2;
    private javax.swing.JRadioButton rbclinica3;
    private javax.swing.JTextArea taObservaciones;
    private javax.swing.JTextField tfAlumno;
    private javax.swing.JTextField tfPaciente;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
